command: [
  "streamlit", 
  "run",
  "app.py"
]

# No compute configuration needed - uses workspace SQL warehouses automatically

env:
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: "SERVING_ENDPOINT"
    value: "databricks-claude-sonnet-4"
  - name: "AUDIT_CATALOG"
    value: "louis"
  - name: "AUDIT_SCHEMA" 
    value: "ucx_assistant_dev"
  - name: "AUDIT_TABLE"
    value: "chat_interactions"
  - name: "AUDIT_DEBUG"
    value: "false"
