# Lakebridge Assistant - Databricks Apps configuration
command:
  - streamlit
  - run
  - app.py

env:
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: CONFIG_FILE
    value: "configs/lakebridge.config.yaml"
  - name: AUDIT_TABLE
    value: "repo_assistants.default.lakebridge_chat_interactions"
