# UCX Assistant - Databricks Apps configuration
command:
  - streamlit
  - run
  - app.py

env:
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: CONFIG_FILE
    value: "configs/ucx.config.yaml"

  - name: AUDIT_TABLE
    value: "repo_assistants.default.ucx_chat_interactions"
