# Databricks Apps deployment configuration
# Deployment settings are now in ../config.yaml under 'deployment' section
# Add environment variables here only if you need to override config.yaml values for specific deployments
command: [
  "streamlit", 
  "run",
  "app.py"
]

env:
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  # Uncomment to override config.yaml values:
  # - name: "SERVING_ENDPOINT"
  #   value: "your-endpoint-name"
  # - name: "AUDIT_TABLE"
  #   value: "catalog.schema.table"
  # - name: "AUDIT_DEBUG"
  #   value: "false"